#ifndef SHOOTAPPCORE_GLOBAL_H
#define SHOOTAPPCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHOOTAPPCORE_LIBRARY)
#  define SHOOTAPPCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHOOTAPPCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHOOTAPPCORE_GLOBAL_H
